import RootLayoutClient from "@/components/RootLayoutClient";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="min-h-screen m-0">
        <RootLayoutClient>{children}</RootLayoutClient>
        </body>
    </html>
  );
}
